### ISSUE TITLE
Feature suggestion: Collapsing the left panel?

### ISSUE THREAD

**Issue by peter-lyons-kehl** [ranmerc/whatsapp-contact-panel-hider#1]
Thank you Kamran. So helpful to keep focus on the message being read/written.

Any chance of collapsing the left panel, too, please?

**Comment by ranmerc** [comment]
I'm glad to hear that you found it helpful! 😀

I have added the collapsing feature in the latest version. I hope you find it productive.

If you have any further comments or suggestion let me know, or else we can close this issue.

**Comment by peter-lyons-kehl** [comment]
Thank you. Unfortunately, I see your new commits in GIT with a new button, but I don't see the new button on my screen. I do have the new version number, I've restarted Firefox:
![image](https://github.com/ranmerc/whatsapp-contact-panel-hider/assets/4270240/88175cc0-e49e-42f0-8100-e2e599f0105b)
![image](https://github.com/ranmerc/whatsapp-contact-panel-hider/assets/4270240/e6211b5e-9aea-4457-9b6e-46efc3f0087b)
![image](https://github.com/ranmerc/whatsapp-contact-panel-hider/assets/4270240/3f90acb8-6986-408c-89ff-9d116966d53a)

**Comment by ranmerc** [comment]
Sorry for the confusion, I should have been more clear in the docs. The collapse button is present at the right middle edge of the left panel. 

Its hidden by default, you need to hover over for it to be visible.

![firefox_3JV9veSBa8](https://github.com/ranmerc/whatsapp-contact-panel-hider/assets/33200113/d2cb020b-994f-4820-b0b8-d9065ec7ab8e)

https://github.com/ranmerc/whatsapp-contact-panel-hider/assets/33200113/47d48304-b897-4fb4-a2fa-f2103b9dcb9e

**Comment by peter-lyons-kehl** [comment]
Wow. Working well.
Thank you.
