### ISSUE TITLE
Is it possible to add a shortcut

### ISSUE THREAD

**Issue by mclorand** [ranmerc/whatsapp-contact-panel-hider#2]
Thanks a lot for this useful plugin. Is there a shortcut to close and open the left panel? Like Alt+X for example

**Comment by ranmerc** [comment]
I am glad you found it helpful!

No, currently there is no such shortcut, and I don't intend to add one. While such a shortcut would be very convenient, I am not comfortable with overriding any keyboard shortcuts a user may already have. I hope you understand my concern.
